/* Generated By:JavaCC: Do not edit this line. CheckerConstants.java */
package checker;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CheckerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASSIGN = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int MULTIPLY = 8;
  /** RegularExpression Id. */
  int DIVIDE = 9;
  /** RegularExpression Id. */
  int LESSTHAN = 10;
  /** RegularExpression Id. */
  int GREATERTHAN = 11;
  /** RegularExpression Id. */
  int EQUALTO = 12;
  /** RegularExpression Id. */
  int NOT = 13;
  /** RegularExpression Id. */
  int INTTYPE = 14;
  /** RegularExpression Id. */
  int STRINGTYPE = 15;
  /** RegularExpression Id. */
  int BOOLEANTYPE = 16;
  /** RegularExpression Id. */
  int PRINT = 17;
  /** RegularExpression Id. */
  int NEWLINE = 18;
  /** RegularExpression Id. */
  int READ = 19;
  /** RegularExpression Id. */
  int SEMI = 20;
  /** RegularExpression Id. */
  int LPAREN = 21;
  /** RegularExpression Id. */
  int RPAREN = 22;
  /** RegularExpression Id. */
  int IF = 23;
  /** RegularExpression Id. */
  int ELSE = 24;
  /** RegularExpression Id. */
  int OPENBRACE = 25;
  /** RegularExpression Id. */
  int CLOSEBRACE = 26;
  /** RegularExpression Id. */
  int CONSTANT = 27;
  /** RegularExpression Id. */
  int DIGIT = 28;
  /** RegularExpression Id. */
  int BOOLEAN = 29;
  /** RegularExpression Id. */
  int VAR = 30;
  /** RegularExpression Id. */
  int LETTER = 31;
  /** RegularExpression Id. */
  int STRING = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"!\"",
    "\"int\"",
    "\"string\"",
    "\"boolean\"",
    "\"print\"",
    "\"newline\"",
    "\"read\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"else\"",
    "\"{\"",
    "\"}\"",
    "<CONSTANT>",
    "<DIGIT>",
    "<BOOLEAN>",
    "<VAR>",
    "<LETTER>",
    "<STRING>",
  };

}
